### ISSUE TITLE
Extrait en sortie complètement différent que celui qu'on a édité dans l'appli

### ISSUE THREAD

**Issue by kerprima** [websealevel/archives-de-bureaulogie#1]
Une fois l'extrait "Cut !", l'extrait n'est pas celui voulu. Encode un autre moment de la vidéo

Et je trouve pas où on rajoute un label #bug, ça me rend fou

**Comment by websealevel** [comment]
Yes,merci c'est parfait. Le label bug c'est la sidebar à droite "Labels", cliquer sur la petite roue dentée "#bug"

**Comment by websealevel** [comment]
@kerprima j'ai poussé un patch. Tu peux me dire si c'est bon pour toi ? Que ça clip le bon extrait ?
