### ISSUE TITLE
Encodage de mauvaise qualité: 480p au lieu de 720p

### ISSUE THREAD

**Issue by kerprima** [websealevel/archives-de-bureaulogie#2]
Semble provenir du téléchargement du fichier source

**Comment by websealevel** [comment]
C'est bien la vidéo source qui est téléchargée en 480p

**Comment by kerprima** [comment]
Ce serait possible d'augmenter la qualité en 1080 plutôt que 720p ?

**Comment by websealevel** [comment]
ça commence à faire du gros fichier, on va trop vite remplir le serveur. Les extraits vont également être plus volumineux (et risque de dépasser la limite d'upload imposée par Twitter). Je ne vois pas l'intérêt d'avoir un clip en 1080p destiné principalement a être embarqué dans un tweet et visionné sur petit écran
